---
#Create the instance
- hosts: all
  become: yes
  become_method: sudo
  tasks:

    - name: Comment out the line '#Again a comment' if it exists
      lineinfile: dest=/etc/nginx/sites-available/default
                  regexp=''
                  state=absent

    - name: Update /etc/nginx/sites-available/default by appending text for the app
      blockinfile:
          dest: /etc/nginx/sites-available/default
          block: |
                 upstream node_cluster {
                     server 127.0.0.1:3010;      # Web instance 1
                     server 127.0.0.1:3000;      # Web instance 2
                 }
                 server {
                     listen 80;
                     server_name yourdomain.com www.yourdomain.com;

                     location / {
                       proxy_set_header X-Real-IP $remote_addr;
                       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                       proxy_set_header Host $http_host;
                       proxy_set_header X-NginX-Proxy true;

                       proxy_pass http://node_cluster/;
                       proxy_redirect off;
                     }
                 }

    - name: Nginx restart
      service: name=nginx state=restarted
      sudo: true
