---
- hosts: localhost
  pre_tasks:
    - name: Search ec2
      ec2_remote_facts:
        region: "us-east-1"
        filters:
          "tag:Group": "Dev_Ruby_Test"
          "tag:Update": "True"
      register: ec2_info

    - name: Show instance info
      debug:
        msg: "{{ ec2_info }}"

#    - debug: var=hostvars[inventory_hostname]
  tasks:
    - name: Instance De-register
      local_action:
        module: ec2_elb
        region: "us-east-1"
        instance_id: "{{ ec2_info.instances[0].id }}"
        ec2_elbs: "ELB-DevOpsTest"
        state: absent
      with_items: ec2_info


#  pre_tasks:
#      - name: Gather ec2 facts
#        action: ec2_facts

#      - name: Instance de-register
#        connection: local
#        local_action:
#            module: ec2_elb
#            region: "{{ ec2_region }}"
#            ec2_elbs: "ELB-DevOpsTest"
#            instance_id: "{{ ansible_ec2_instance_id }}"
#            state: 'absent'
