---
#Create the Subnets

#Create the roles

#Create the ELB

#Create the Securtity Groups

#Create the instance
- hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Gathering ec2 facts
      action: ec2_facts
    - name: Instance De-register
      local_action:
        module: ec2_elb
        instance_id: i-073fc19a  #"{{ ansible_ec2_instance_id }}"
      state: absent

  roles:
    - ec2_creation
    
  post_tasks:
    - name: Instance Register
      local_action:
        module: ec2_elb
        instance_id: i-073fc19a #"{{ ansible_ec2_instance_id }}"
        ec2_elbs: ELB-DevOpsTest #"{{ item }}"
        state: present
      with_items: ec2_elbs
