---
#Create the instance
- hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - ec2_creation

#Configure and install all we need
- hosts: ec2hosts
  vars:
    apache_vhosts_enabled:
      servername: ec2hosts


  gather_facts: true
  remote_user: ec2-user


  roles:
    - common # install listing of yum repos needed on the server
    - rubyServer
    - app_install

  tasks:
    - pause: seconds=5 # allow install/httpd to come back online
