---
#Create the Subnets

#Create the roles

#Create the ELB

#Create the Securtity Groups

#Create the instance
- hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - ec2_creation
    - common
#    - devops-testapp
