---
- name: Search ec2
  ec2_remote_facts:
    region: "us-east-1"
    filters:
      "tag:Group": "Dev_Ruby_Test"
      "tag:Update": "True"
  register: ec2_info

- name: Show instance info
  debug:
    msg: "{{ ec2_info }}"
