---
#
# Playbook:
#
# Role variables:
# - aws.region:  AWS region
# - aws.ec2_elb: AWS Elastic Load Balancer name that the node belongs to
#
#

- hosts: all
  serial: 1

# Pre tasks should disable monitoring

  pre_tasks:
    - name: Gather EC2 facts
      ec2_facts:

    - name: Remove node from ELB
      local_action: ec2_elb
      args:
        instance_id: "{{ ansible_ec2_instance_id }}"
        region:      "{{ aws.region }}"
        ec2_elbs:    "{{ aws.ec2_elb }}"
        state:       'absent'

  - include: provisioning.yml
