---
- name: Search ec2
  ec2_remote_facts:
    region: "us-east-1"
    filters:
      instance-state-name: running
      "tag:Group": "Dev_Ruby_Test"
  register: ec2_info

#- name: Debug EC2 facts
#  debug: msg="{{ ec2_info }}"  Dev_Test_Update
