---

- name: register/de-register EC2 instances in ELB
  ec2_elb:
    region="{{ instance_values['aws_elb_region'] }}"
    ec2_elbs="{{ instance_values['aws_elb_ec2_elbs']}}"
    instance_id="{{instance_values['aws_elb_instance_id']}}"
    state="{{ instance_values['aws_elb_state'] }}"
