---
- hosts: tag_Name_ruby_ec2_test_onstack
  gather_facts: True
  connection: local
  vars_files:
  - ./vars/main.yml

  tasks:
#    - name: gather ec2 facts
#      ec2_facts:
#    - debug: msg={{ ansible_ec2_instance_id }}
  #  - action: ec2_facts
  #  - debug: var=ansible_ec2_instance_id
    - local_action: ec2_facts
#    - debug: msg="{{ hostvars['ec2_id']}}"
    - name: terminating old instances
      local_action:
        module: ec2
        state: 'absent'
        region: '{{ env_region }}'
        keypair: '{{ keypair }}'
        instance_ids: "{{ ec2_id }}"
