---
#- name: update development packages
#  shell: yum groupinstall -y development
#  sudo: yes

- name: install common packages
  yum:
    name: "{{ item }}"
    state: latest
  #  become: sudo
  with_items: "{{packages}}"
