---
- name: Check if instance exists
  ec2_instances:
    region: "us-east-1"
    tag: "ruby_ec2_test_onstack"
  register: ec2_instances

- name: Get instance information
  debug:
    msg: "{{ instance_values }}"

- name: collect instance
  ec2:
    region: "{{ instance_values['region'] }}"
    zone: "{{ instance_values['zone'] }}"
    keypair: "{{ instance_values['key_pair'] }}"
    group: "{{ instance_values['security_groups'] }}"
    instance_type: "{{ instance_values['instance_type'] }}"
    image: "{{ instance_values['image_id'] }}"
    count: 1
    wait: yes
    instance_tags:
      Name: "{{ instance_values['name'] }}"
  when: ec2_instances.instances[instance_values['name']]|default("") == ""
  register: ec2_info

- name: Debug EC2 facts
  debug: msg="{{ ec2_instances.instances }}"
