---
default_values:
  instance_type: "t2.micro"
  region: "us-east-1"
#  zone: "us-east-1a"
  key_pair: "DevOps-Test"
  image_id: "ami-08111162" #Amazon Linux 64 bits blank slate
  security_groups: ["DevOps-Test"]
  name: "ruby_ec2_test_onstack"
  count: "1"

instance_values:
  name: "{{ default_values['name'] }}"
  instance_type: "{{ default_values['instance_type'] }}"
  region: "{{ default_values['region'] }}"
#  zone: "{{ default_values['zone'] }}"
  key_pair: "{{ default_values['key_pair'] }}"
  image_id: "{{ default_values['image_id'] }}"
  security_groups: "{{ default_values['security_groups'] }}"
  count: "{{ default_values['count'] }}"
